// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCBsTpYkKiIIffQhOeVP2QApToAsbBsn4',
    appId: '1:420306755386:web:9dbdace7db965383317a03',
    messagingSenderId: '420306755386',
    projectId: 'otp-auth-2bab5',
    authDomain: 'otp-auth-2bab5.firebaseapp.com',
    storageBucket: 'otp-auth-2bab5.appspot.com',
    measurementId: 'G-D7SP5JF7SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9zvlgwb-k2hB284LMNXfhwEMJ6_hGyU',
    appId: '1:420306755386:android:02d82b779d648c21317a03',
    messagingSenderId: '420306755386',
    projectId: 'otp-auth-2bab5',
    storageBucket: 'otp-auth-2bab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUWhJWNSOGLz82TfufYD3YgaMlPxsQ3WA',
    appId: '1:420306755386:ios:c82737824c50f2a8317a03',
    messagingSenderId: '420306755386',
    projectId: 'otp-auth-2bab5',
    storageBucket: 'otp-auth-2bab5.appspot.com',
    iosBundleId: 'com.example.otpAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUWhJWNSOGLz82TfufYD3YgaMlPxsQ3WA',
    appId: '1:420306755386:ios:f8573ad97b88ddd1317a03',
    messagingSenderId: '420306755386',
    projectId: 'otp-auth-2bab5',
    storageBucket: 'otp-auth-2bab5.appspot.com',
    iosBundleId: 'com.example.otpAuth.RunnerTests',
  );
}
